version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: arsip-api
    ports:
      - "8888:8888"
    environment:
      - MEILI_URL=http://meilisearch:7700
      - MEILI_KEY=arsipsearch2024
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root123
      - MYSQL_DB=arsipserverdb2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8888 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arsip-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
